server:
  port: 80
  context-path: /

spring:
  application:
    name: wtx
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.wtxcloud.cn:3306/wtx_cloud?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: a147258
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8 #初始化连接大小
      min-idle: 5 #最小空闲连接数
      max-active: 10 #最大连接数
      query-timeout: 6000 #查询超时时间
      transaction-query-timeout: 6000 #事务查询超时时间
      remove-abandoned-timeout: 1800 #关闭空闲连接超时时间
      filter-class-names: stat
      filters: stat,config

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.pojo,com.entity
  configuration:
    map-underscore-to-camel-case: true
  mapperLocations: classpath:mapper/*.xml
